const type = {
  SET_PLAYLIST: 'SET_PLAYLIST',
  SET_CURRENT_INDEX: 'SET_CURRENT_INDEX',
  SET_PLAYING: 'SET_PLAYING',
  SET_PLAYMODE: 'SET_PLAYMODE',
  SET_RANDOM_LIST: 'SET_RANDOM_LIST',
  SET_CURRENT_SONG: 'SET_CURRENT_SONG',
  SET_SEQUENCE_LIST: 'SET_SEQUENCE_LIST',
  SET_FULL_SCREEN: 'SET_FULL_SCREEN',
  UPDATE_SEQUENCE_LIST: 'UPDATE_SEQUENCE_LIST',
  UPDATE_PLAYLIST: 'UPDATE_PLAYLIST'
}

export default type
